# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradPlusAdSDK', '15.3.0'
  pod 'Ads-CN/BUAdSDK', '7.4.0.5'
  pod 'Ads-CN/CSJMediation', '7.4.0.5'

end
