# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradPlusAdSDK', '14.4.1'
  pod 'Ads-CN/BUAdSDK', '7.1.0.9'
  pod 'Ads-CN/CSJMediation', '7.1.0.9'

end
