# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradPlusAdSDK', '14.2.0'
  pod 'Ads-CN/BUAdSDK', '6.9.1.2'
  pod 'Ads-CN/CSJMediation', '6.9.1.2'

end
